local gt = this.getroottable();
if (!("Companions" in gt.Const))
{
	gt.Const.Companions <- {};
}
gt.Const.Companions.AttainableQuirks <- [
	// PERKS
	"scripts/skills/perks/perk_fast_adaption",
	"scripts/skills/perks/perk_crippling_strikes",
	"scripts/skills/perks/perk_colossus",
	"scripts/skills/perks/perk_nine_lives",
//	"scripts/skills/perks/perk_bags_and_belts",
	"scripts/skills/perks/perk_pathfinder",
//	"scripts/skills/perks/perk_adrenalin",
//	"scripts/skills/perks/perk_recover",
//	"scripts/skills/perks/perk_student",
	"scripts/skills/perks/perk_coup_de_grace",
//	"scripts/skills/perks/perk_bullseye",
	"scripts/skills/perks/perk_dodge",
//	"scripts/skills/perks/perk_fortified_mind",
//	"scripts/skills/perks/perk_hold_out",
	"scripts/skills/perks/perk_steel_brow",
//	"scripts/skills/perks/perk_quick_hands",
//	"scripts/skills/perks/perk_gifted",
	"scripts/skills/perks/perk_backstabber",
	"scripts/skills/perks/perk_anticipation",
//	"scripts/skills/perks/perk_shield_expert",
//	"scripts/skills/perks/perk_brawny",
//	"scripts/skills/perks/perk_relentless",
//	"scripts/skills/perks/perk_rotation",
//	"scripts/skills/perks/perk_rally_the_troops",
//	"scripts/skills/perks/perk_taunt",
//	"scripts/skills/perks/perk_mastery_mace",
//	"scripts/skills/perks/perk_mastery_flail",
//	"scripts/skills/perks/perk_mastery_hammer",
//	"scripts/skills/perks/perk_mastery_axe",
//	"scripts/skills/perks/perk_mastery_cleaver",
//	"scripts/skills/perks/perk_mastery_sword",
//	"scripts/skills/perks/perk_mastery_dagger",
//	"scripts/skills/perks/perk_mastery_polearm",
//	"scripts/skills/perks/perk_mastery_spear",
//	"scripts/skills/perks/perk_mastery_crossbow",
//	"scripts/skills/perks/perk_mastery_bow",
//	"scripts/skills/perks/perk_mastery_throwing",
//	"scripts/skills/perks/perk_reach_advantage",
	"scripts/skills/perks/perk_overwhelm",
//	"scripts/skills/perks/perk_lone_wolf",
	"scripts/skills/perks/perk_underdog",
//	"scripts/skills/perks/perk_footwork",
	"scripts/skills/perks/perk_berserk",
	"scripts/skills/perks/perk_head_hunter",
	"scripts/skills/perks/perk_nimble",
//	"scripts/skills/perks/perk_battle_forged",
	"scripts/skills/perks/perk_fearsome",
//	"scripts/skills/perks/perk_duelist",
	"scripts/skills/perks/perk_killing_frenzy",
//	"scripts/skills/perks/perk_indomitable", - Never seen it used
//	"scripts/skills/perks/perk_battle_flow",
	"scripts/skills/perks/perk_devastating_strikes",
	"scripts/skills/perks/perk_battering_ram",
//	"scripts/skills/perks/perk_steadfast",
	"scripts/skills/perks/perk_stalwart",
	"scripts/skills/perks/perk_sundering_strikes",
	"scripts/skills/perks/perk_devastating_strikes",
	"scripts/skills/perks/perk_double_strike",
	"scripts/skills/perks/perk_slaughterer",
	"scripts/skills/perks/perk_ironside",
	"scripts/skills/perks/perk_last_stand",
	"scripts/skills/perks/perk_lookout",
	"scripts/skills/perks/perk_push_the_advantage",
	"scripts/skills/perks/perk_trophy_hunter",
	"scripts/skills/perks/perk_vengeance",
	
// PERKS - Legends
    "scripts/skills/perks/perk_legend_escape_artist",
    "scripts/skills/perks/perk_legend_terrifying_visage",   
//  "scripts/skills/perks/perk_legend_poison_immunity",  // -> Make sure to change properties of creatures to give it as bonus perk instead of unaffected
    "scripts/skills/perks/perk_legend_onslaught",  
//  "scripts/skills/perks/perk_legend_assured_conquest",  
    "scripts/skills/perks/perk_legend_alert",
//  "scripts/skills/perks/perk_legend_second_wind", 
	"scripts/skills/perks/perk_legend_battleheart",  
	"scripts/skills/perks/perk_legend_blend_in",
	"scripts/skills/perks/perk_legend_bloodbath",
	"scripts/skills/perks/perk_legend_clarity",
	"scripts/skills/perks/perk_legend_freedom_of_movement",
	"scripts/skills/perks/perk_legend_hair_splitter",
	"scripts/skills/perks/perk_legend_heightened_reflexes",
	"scripts/skills/perks/perk_legend_lacerate",
	"scripts/skills/perks/perk_legend_lithe",

	// TRAITS
//	"scripts/skills/traits/huge_trait",   Effectively a nerf, and hurts the high tier stuff less than dogs and such
//	"scripts/skills/traits/lucky_trait",
//	"scripts/skills/traits/delz_darkvision_trait",
	// ACTIVES, EFFECTS, QUIRKS
//	"scripts/companions/quirks/companions_berserker_rage", // Berserker
//	"scripts/companions/quirks/companions_poisonous",
//	"scripts/companions/quirks/companions_healthy",
//	"scripts/companions/quirks/companions_soften_blows",
//	"scripts/companions/quirks/companions_regenerative",
//	"scripts/companions/quirks/companions_delz_ferocity",
//	"scripts/companions/quirks/companions_delz_tenacity"
];
gt.Const.Companions.AttainableQuirksDLCUnhold <- [ // Beasts and Exploration
];
gt.Const.Companions.AttainableQuirksDLCWildmen <- [ // Warriors of the North
];
gt.Const.Companions.AttainableQuirksDLCDesert <- [ // Blazing Deserts
//	"scripts/skills/actives/throw_dirt_skill"
];
gt.Const.Companions.AttainableQuirksBeasts <- [ // Beast-specific Quirks
	"scripts/skills/perks/perk_fortified_mind",
	"scripts/skills/perks/perk_hold_out",
	"scripts/skills/perks/perk_relentless",
	"scripts/skills/perks/perk_legend_poison_immunity",
	"scripts/skills/perks/perk_legend_assured_conquest",
	"scripts/skills/perks/perk_legend_second_wind",  
	"scripts/skills/perks/perk_feint",
	"scripts/skills/perks/perk_battle_flow",
	"scripts/skills/perks/perk_rebound",
	"scripts/skills/perks/perk_steadfast",
	"scripts/skills/perks/perk_legend_back_to_basics"
	"scripts/skills/perks/perk_legend_muscularity",
	"scripts/skills/perks/perk_legend_mind_over_body",
	"scripts/skills/perks/perk_legend_taste_the_pain",
	"scripts/skills/perks/perk_ptr_deep_impact",
	"scripts/skills/perks/perk_ptr_deep_impact",
];
gt.Const.Companions.AttainableQuirksPTR <- [
	"scripts/skills/perks/perk_ptr_bear_down",
	"scripts/skills/perks/perk_ptr_between_the_ribs",
	"scripts/skills/perks/perk_ptr_bloodbath",
	"scripts/skills/perks/perk_ptr_bone_breaker",
	"scripts/skills/perks/perk_ptr_bully",
	"scripts/skills/perks/perk_ptr_cull",
//	"scripts/skills/perks/perk_ptr_deep_cuts",
	"scripts/skills/perks/perk_ptr_dent_armor",
	"scripts/skills/perks/perk_ptr_dismantle",
	"scripts/skills/perks/perk_ptr_dismemberment",
	"scripts/skills/perks/perk_ptr_dynamic_duo",
	"scripts/skills/perks/perk_ptr_exploit_opening",
	"scripts/skills/perks/perk_ptr_fluid_weapon",
	"scripts/skills/perks/perk_ptr_formidable_approach",
	"scripts/skills/perks/perk_ptr_fresh_and_furious",
	"scripts/skills/perks/perk_ptr_from_all_sides",
	"scripts/skills/perks/perk_ptr_fruits_of_labor",
	"scripts/skills/perks/perk_ptr_head_smasher",
	"scripts/skills/perks/perk_ptr_king_of_all_weapons",
	"scripts/skills/perks/perk_ptr_know_their_weakness",
	"scripts/skills/perks/perk_ptr_light_weapon",
	"scripts/skills/perks/perk_ptr_mauler",
	"scripts/skills/perks/perk_ptr_menacing",
	"scripts/skills/perks/perk_ptr_pattern_recognition",
	"scripts/skills/perks/perk_ptr_personal_armor",
//	"scripts/skills/perks/perk_ptr_pointy_end",
	"scripts/skills/perks/perk_ptr_push_it",
//	"scripts/skills/perks/perk_ptr_rattle",
	"scripts/skills/perks/perk_ptr_sanguinary",
	"scripts/skills/perks/perk_ptr_small_target",
	"scripts/skills/perks/perk_ptr_soft_metal",
	"scripts/skills/perks/perk_ptr_strength_in_numbers",
	"scripts/skills/perks/perk_ptr_survival_instinct",
	"scripts/skills/perks/perk_ptr_tempo",
	"scripts/skills/perks/perk_ptr_tunnel_vision",
	"scripts/skills/perks/perk_ptr_unstoppable",
	"scripts/skills/perks/perk_ptr_utilitarian",
	"scripts/skills/perks/perk_ptr_vigilant",
	"scripts/skills/perks/perk_ptr_wear_them_down",	
];
gt.Const.Companions.AttainableQuirksBeastsPTR <- [
	"scripts/skills/perks/perk_ptr_bloodlust",
	"scripts/skills/perks/perk_ptr_bulwark",
	"scripts/skills/perks/perk_ptr_exude_confidence",
	"scripts/skills/perks/perk_ptr_man_of_steel",
	"scripts/skills/perks/perk_ptr_the_rush_of_battle",
	"scripts/skills/perks/perk_ptr_wears_it_well",	
];
gt.Const.Companions.SerializeQuirks <- [
	// PERKS
	"perk.fast_adaption",
	"perk.crippling_strikes",
	"perk.colossus",
	"perk.nine_lives",
	"perk.bags_and_belts",
	"perk.pathfinder",
	"perk.adrenaline",
	"perk.recover",
	"perk.student",
	"perk.coup_de_grace",
	"perk.bullseye",
	"perk.dodge",
	"perk.fortified_mind",
	"perk.hold_out",
	"perk.steel_brow",
	"perk.quick_hands",
	"perk.gifted",
	"perk.backstabber",
	"perk.anticipation",
	"perk.shield_expert",
	"perk.brawny",
	"perk.relentless",
	"perk.rotation",
	"perk.rally_the_troops",
	"perk.taunt",
	"perk.mastery.mace",
	"perk.mastery.flail",
	"perk.mastery.hammer",
	"perk.mastery.axe",
	"perk.mastery.cleaver",
	"perk.mastery.sword",
	"perk.mastery.dagger",
	"perk.mastery.polearm",
	"perk.mastery.spear",
	"perk.mastery.crossbow",
	"perk.mastery.bow",
	"perk.mastery.throwing",
	"perk.reach_advantage",
	"perk.overwhelm",
	"perk.lone_wolf",
	"perk.underdog",
	"perk.footwork",
	"perk.berserk",
	"perk.head_hunter",
	"perk.nimble",
	"perk.battle_forged",
	"perk.fearsome",
	"perk.duelist",
	"perk.killing_frenzy",
	"perk.indomitable",
	"perk.battle_flow",
	"perk.devastating_strikes",
	"perk.battering_ram",
	"perk.steadfast",
	"perk.stalwart",
	"perk.sundering_strikes",
	"perk.feint"
	// BEAST-SPECIFICS
	"quirk.good_boy",
	// TRAITS
	"trait.huge",
	"trait.lucky",
	"trait.delz_darkvision",
	// ACTIVES, EFFECTS, QUIRKS
	"actives.throw_dirt",
	"quirk.berserker_rage",
	"quirk.poison_coat",
	"quirk.healthy",
	"quirk.soften_blows",
	"quirk.regenerative",
    "quirk.delz_ferocity",
    "quirk.delz_tenacity",	
	// Legends
    "perk.legend_escape_artist",
    "perk.legend_terrifying_visage",
    "perk.slaughterer",
    "perk.legend_poison_immunity",
    "perk.legend_onslaught",
    "perk.legend_assured_conquest",
    "perk.legend_alert",
    "perk.double_strike",
    "perk.legend_second_wind",
    "perk.return_favor",
];
gt.Const.Companions.DeserializeQuirks <- [
	// PERKS
	"scripts/skills/perks/perk_fast_adaption",
	"scripts/skills/perks/perk_crippling_strikes",
	"scripts/skills/perks/perk_colossus",
	"scripts/skills/perks/perk_nine_lives",
	"scripts/skills/perks/perk_bags_and_belts",
	"scripts/skills/perks/perk_pathfinder",
	"scripts/skills/perks/perk_adrenalin",
	"scripts/skills/perks/perk_recover",
	"scripts/skills/perks/perk_student",
	"scripts/skills/perks/perk_coup_de_grace",
	"scripts/skills/perks/perk_bullseye",
	"scripts/skills/perks/perk_dodge",
	"scripts/skills/perks/perk_fortified_mind",
	"scripts/skills/perks/perk_hold_out",
	"scripts/skills/perks/perk_steel_brow",
	"scripts/skills/perks/perk_quick_hands",
	"scripts/skills/perks/perk_gifted",
	"scripts/skills/perks/perk_backstabber",
	"scripts/skills/perks/perk_anticipation",
	"scripts/skills/perks/perk_shield_expert",
	"scripts/skills/perks/perk_brawny",
	"scripts/skills/perks/perk_relentless",
	"scripts/skills/perks/perk_rotation",
	"scripts/skills/perks/perk_rally_the_troops",
	"scripts/skills/perks/perk_taunt",
	"scripts/skills/perks/perk_mastery_mace",
	"scripts/skills/perks/perk_mastery_flail",
	"scripts/skills/perks/perk_mastery_hammer",
	"scripts/skills/perks/perk_mastery_axe",
	"scripts/skills/perks/perk_mastery_cleaver",
	"scripts/skills/perks/perk_mastery_sword",
	"scripts/skills/perks/perk_mastery_dagger",
	"scripts/skills/perks/perk_mastery_polearm",
	"scripts/skills/perks/perk_mastery_spear",
	"scripts/skills/perks/perk_mastery_crossbow",
	"scripts/skills/perks/perk_mastery_bow",
	"scripts/skills/perks/perk_mastery_throwing",
	"scripts/skills/perks/perk_reach_advantage",
	"scripts/skills/perks/perk_overwhelm",
	"scripts/skills/perks/perk_lone_wolf",
	"scripts/skills/perks/perk_underdog",
	"scripts/skills/perks/perk_footwork",
	"scripts/skills/perks/perk_berserk",
	"scripts/skills/perks/perk_head_hunter",
	"scripts/skills/perks/perk_nimble",
	"scripts/skills/perks/perk_battle_forged",
	"scripts/skills/perks/perk_fearsome",
	"scripts/skills/perks/perk_duelist",
	"scripts/skills/perks/perk_killing_frenzy",
	"scripts/skills/perks/perk_indomitable",
	"scripts/skills/perks/perk_battle_flow",
	"scripts/skills/perks/perk_devastating_strikes",
	"scripts/skills/perks/perk_battering_ram",
	"scripts/skills/perks/perk_steadfast",
	"scripts/skills/perks/perk_stalwart",
	"scripts/skills/perks/perk_sundering_strikes",
	"scripts/skills/perks/perk_feint"
	// BEAST-SPECIFICS
	"scripts/companions/quirks/companions_good_boy",
	// TRAITS
	"scripts/skills/traits/huge_trait",
	"scripts/skills/traits/lucky_trait",
	"scripts/skills/traits/delz_darkvision_trait",
	// ACTIVES, EFFECTS, QUIRKS
	"scripts/skills/actives/throw_dirt_skill",
	"scripts/companions/quirks/companions_berserker_rage",
	"scripts/companions/quirks/companions_poisonous",
	"scripts/companions/quirks/companions_healthy",
	"scripts/companions/quirks/companions_soften_blows",
	"scripts/companions/quirks/companions_regenerative",
	"scripts/companions/quirks/companions_delz_ferocity",
	"scripts/companions/quirks/companions_delz_tenacity",
	// Legends
    "scripts/skills/perks/perk_legend_escape_artist",
    "scripts/skills/perks/perk_legend_terrifying_visage",  
    "scripts/skills/perks/perk_slaughterer",  
    "scripts/skills/perks/perk_legend_poison_immunity", 
    "scripts/skills/perks/perk_legend_onslaught",  
    "scripts/skills/perks/perk_legend_assured_conquest",  
    "scripts/skills/perks/perk_legend_alert",
    "scripts/skills/perks/perk_double_strike",  
    "scripts/skills/perks/perk_legend_second_wind",  
    "scripts/skills/perks/perk_return_favor",
];
