local gt = this.getroottable();

if (!("Companions" in gt.Const))
{
	gt.Const.Companions <- {};
}

gt.Const.Companions.AttainableQuirks <- [
	"scripts/skills/perks/perk_fast_adaption",
	"scripts/skills/perks/perk_crippling_strikes",
	"scripts/skills/perks/perk_colossus",
	"scripts/skills/perks/perk_nine_lives",
	"scripts/skills/perks/perk_pathfinder",
	"scripts/skills/perks/perk_adrenalin",
	"scripts/skills/perks/perk_coup_de_grace",
	"scripts/skills/perks/perk_dodge",
	"scripts/skills/perks/perk_hold_out",
	"scripts/skills/perks/perk_steel_brow",
	"scripts/skills/perks/perk_backstabber",
	"scripts/skills/perks/perk_anticipation",
	"scripts/skills/perks/perk_relentless",
	"scripts/skills/perks/perk_overwhelm",
	"scripts/skills/perks/perk_lone_wolf",
	"scripts/skills/perks/perk_underdog",
	"scripts/skills/perks/perk_berserk",
	"scripts/skills/perks/perk_head_hunter",
	"scripts/skills/perks/perk_nimble",
	"scripts/skills/perks/perk_fearsome",
	"scripts/skills/perks/perk_killing_frenzy",
	"scripts/skills/perks/perk_indomitable",
	"scripts/skills/perks/perk_battle_flow",
	"scripts/skills/perks/perk_devastating_strikes",
	"scripts/skills/perks/perk_battering_ram",
	"scripts/skills/perks/perk_stalwart",
	"scripts/skills/perks/perk_sundering_strikes",
	"scripts/skills/traits/huge_trait",
	"scripts/skills/traits/lucky_trait",
	"scripts/companions/quirks/companions_berserker_rage",
	"scripts/companions/quirks/companions_healthy",
	"scripts/companions/quirks/companions_soften_blows"
];
gt.Const.Companions.AttainableQuirksDLCUnhold <- [];
gt.Const.Companions.AttainableQuirksDLCWildmen <- [];
gt.Const.Companions.AttainableQuirksDLCDesert <- [
	"scripts/skills/actives/throw_dirt_skill"
];
gt.Const.Companions.AttainableQuirksBeasts <- [
	"scripts/companions/quirks/companions_poisonous"
];
gt.Const.Companions.SerializeQuirks <- [
	"Fast Adaptation",
	"Crippling Strikes",
	"Colossus",
	"Nine Lives",
	"Bags and Belts",
	"Pathfinder",
	"Adrenaline",
	"Recover",
	"Student",
	"Executioner",
	"Bullseye",
	"Dodge",
	"Fortified Mind",
	"Resilient",
	"Steel Brow",
	"Quick Hands",
	"Gifted",
	"Backstabber",
	"Anticipation",
	"Shield Expert",
	"Brawny",
	"Relentless",
	"Rotation",
	"Rally the Troops",
	"Taunt",
	"Mace Mastery",
	"Flail Mastery",
	"Hammer Mastery",
	"Axe Mastery",
	"Cleaver Mastery",
	"Sword Mastery",
	"Dagger Mastery",
	"Polearm Mastery",
	"Spear Mastery",
	"Crossbow & Firearms Mastery",
	"Bow Mastery",
	"Throwing Mastery",
	"Reach Advantage",
	"Overwhelm",
	"Lone Wolf",
	"Underdog",
	"Footwork",
	"Berserk",
	"Head Hunter",
	"Nimble",
	"Battle Forged",
	"Fearsome",
	"Duelist",
	"Killing Frenzy",
	"Indomitable",
	"Battle Flow",
	"Devastating Strikes",
	"Battering Ram",
	"Steadfast",
	"Stalwart",
	"Sundering Strikes",
	"Good Boy",
	"Huge",
	"Lucky",
	"Throw Dirt",
	"Rage",
	"Poisonous",
	"Healthy",
	"Soften Blows"
];
gt.Const.Companions.DeserializeQuirks <- [
	"scripts/skills/perks/perk_fast_adaption",
	"scripts/skills/perks/perk_crippling_strikes",
	"scripts/skills/perks/perk_colossus",
	"scripts/skills/perks/perk_nine_lives",
	"scripts/skills/perks/perk_bags_and_belts",
	"scripts/skills/perks/perk_pathfinder",
	"scripts/skills/perks/perk_adrenalin",
	"scripts/skills/perks/perk_recover",
	"scripts/skills/perks/perk_student",
	"scripts/skills/perks/perk_coup_de_grace",
	"scripts/skills/perks/perk_bullseye",
	"scripts/skills/perks/perk_dodge",
	"scripts/skills/perks/perk_fortified_mind",
	"scripts/skills/perks/perk_hold_out",
	"scripts/skills/perks/perk_steel_brow",
	"scripts/skills/perks/perk_quick_hands",
	"scripts/skills/perks/perk_gifted",
	"scripts/skills/perks/perk_backstabber",
	"scripts/skills/perks/perk_anticipation",
	"scripts/skills/perks/perk_shield_expert",
	"scripts/skills/perks/perk_brawny",
	"scripts/skills/perks/perk_relentless",
	"scripts/skills/perks/perk_rotation",
	"scripts/skills/perks/perk_rally_the_troops",
	"scripts/skills/perks/perk_taunt",
	"scripts/skills/perks/perk_mastery_mace",
	"scripts/skills/perks/perk_mastery_flail",
	"scripts/skills/perks/perk_mastery_hammer",
	"scripts/skills/perks/perk_mastery_axe",
	"scripts/skills/perks/perk_mastery_cleaver",
	"scripts/skills/perks/perk_mastery_sword",
	"scripts/skills/perks/perk_mastery_dagger",
	"scripts/skills/perks/perk_mastery_polearm",
	"scripts/skills/perks/perk_mastery_spear",
	"scripts/skills/perks/perk_mastery_crossbow",
	"scripts/skills/perks/perk_mastery_bow",
	"scripts/skills/perks/perk_mastery_throwing",
	"scripts/skills/perks/perk_reach_advantage",
	"scripts/skills/perks/perk_overwhelm",
	"scripts/skills/perks/perk_lone_wolf",
	"scripts/skills/perks/perk_underdog",
	"scripts/skills/perks/perk_footwork",
	"scripts/skills/perks/perk_berserk",
	"scripts/skills/perks/perk_head_hunter",
	"scripts/skills/perks/perk_nimble",
	"scripts/skills/perks/perk_battle_forged",
	"scripts/skills/perks/perk_fearsome",
	"scripts/skills/perks/perk_duelist",
	"scripts/skills/perks/perk_killing_frenzy",
	"scripts/skills/perks/perk_indomitable",
	"scripts/skills/perks/perk_battle_flow",
	"scripts/skills/perks/perk_devastating_strikes",
	"scripts/skills/perks/perk_battering_ram",
	"scripts/skills/perks/perk_steadfast",
	"scripts/skills/perks/perk_stalwart",
	"scripts/skills/perks/perk_sundering_strikes",
	"scripts/companions/quirks/companions_good_boy",
	"scripts/skills/traits/huge_trait",
	"scripts/skills/traits/lucky_trait",
	"scripts/skills/actives/throw_dirt_skill",
	"scripts/companions/quirks/companions_berserker_rage",
	"scripts/companions/quirks/companions_poisonous",
	"scripts/companions/quirks/companions_healthy",
	"scripts/companions/quirks/companions_soften_blows"
];

